### ISSUE TITLE
Validation extract hostname from running config error

### ISSUE THREAD

**Issue by kylinsoong** [kylinsoong/f5-tmsh-generator#17]
Reproduce:

~~~
% ./f5-tmsh-validation.py config/BH-BF2M1-HLW_APP-L3600-2A.com_11.16.176.91.running-config.txt ~/Downloads/1102/01.xlsx
Traceback (most recent call last):
  File "/Users/k.song/src/f5-tmsh-generator/./f5-tmsh-validation.py", line 977, in <module>
    device_info = data_collect_system_extract_hostname(bigip_running_config)
  File "/Users/k.song/src/f5-tmsh-generator/./f5-tmsh-validation.py", line 882, in data_collect_system_extract_hostname
    return (devices[0].hostname, devices[0].management_ip, devices[0].version)
IndexError: list index out of range
~~~

**Comment by kylinsoong** [comment]
Update: root reason for failed

* V10 do not contains `cm`
