### ISSUE TITLE
Handle  unexpected route gateway

### ISSUE THREAD

**Issue by kylinsoong** [kylinsoong/f5-tmsh-generator#18]
~~~
% ./f5-tmsh-validation.py config/BH-BF2M1-HLW_APP-L2000-1B.com_11.16.160.28.running-config ~/Downloads/1102/02.xlsx
[<f5bigip.configParse.BIGIPNetRoute object at 0x1060e5100>, <f5bigip.configParse.BIGIPNetRoute object at 0x1060e5160>]
11.16.160.30
None
Traceback (most recent call last):
  File "/Users/k.song/src/f5-tmsh-generator/./f5-tmsh-validation.py", line 993, in <module>
    spec_validation_list.append(SpecRouteConfiguration(SPEC_ITEM_INEXROUTER_CONF, device_info[0], device_info[1], device_info[2], bigip_running_config))
  File "/Users/k.song/src/f5-tmsh-generator/./f5-tmsh-validation.py", line 743, in __init__
    self.parse()
  File "/Users/k.song/src/f5-tmsh-generator/./f5-tmsh-validation.py", line 827, in parse
    validation_results = spec_route_configuration_validation(self.data)
  File "/Users/k.song/src/f5-tmsh-generator/./f5-tmsh-validation.py", line 324, in spec_route_configuration_validation
    ip_addr = ipaddress.ip_address(i.gw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: None does not appear to be an IPv4 or IPv6 address
~~~

**Comment by kylinsoong** [comment]
Update: Root reason for failed validation:

The running configure has unexpected characters.
